'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { tracks, type Track } from '@/data/tracks';

declare global { interface Window { YT: any; onYouTubeIframeAPIReady: () => void } }
const speeds = [.75, 1, 1.25, 1.5];
const stamp = () => new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true }).format(new Date());
const dayStamp = () => new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());
const niceTime = (value: number) => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(Math.floor(value % 60)).padStart(2, '0')}`;

function Glyph({ type }: { type: string }) { return <span className={`glyph ${type}`} aria-hidden="true"><i /><b /></span>; }

function WindowBox({ title, children, className = '', onClose }: { title: string; children: React.ReactNode; className?: string; onClose?: () => void }) {
  return <section className={`window-box ${className}`}><header><span className="win-dot" />{title}<button onClick={onClose} aria-label={`Close ${title}`}>×</button></header>{children}</section>;
}

export default function Home() {
  const [boot, setBoot] = useState(true), [menu, setMenu] = useState(false), [playlist, setPlaylist] = useState(true), [off, setOff] = useState(false), [saver, setSaver] = useState(false), [context, setContext] = useState<{ x: number; y: number } | null>(null), [nowPos, setNowPos] = useState<{ x: number; y: number } | null>(null);
  const [active, setActive] = useState(0), [playing, setPlaying] = useState(false), [elapsed, setElapsed] = useState(0), [duration, setDuration] = useState(0), [volume, setVolume] = useState(72), [speed, setSpeed] = useState(1), [clock, setClock] = useState(stamp()), [listeners, setListeners] = useState(1), [weather, setWeather] = useState('28° Clear'), [shimmer, setShimmer] = useState(false);
  const player = useRef<any>(null), playerMount = useRef<HTMLDivElement>(null), activeRef = useRef(0), dragged = useRef(false), lastInput = useRef(Date.now());
  const track = tracks[active]; activeRef.current = active;

  const load = useCallback((index: number, autoplay = true) => { const i = (index + tracks.length) % tracks.length; setActive(i); setElapsed(0); if (player.current) player.current.loadVideoById({ videoId: tracks[i].videoId, startSeconds: 0 }); if (!autoplay && player.current) player.current.pauseVideo(); setPlaying(autoplay); }, []);
  const toggle = () => { if (!player.current) return; playing ? player.current.pauseVideo() : player.current.playVideo(); setPlaying(!playing); };
  const seek = (time: number) => { player.current?.seekTo(time, true); setElapsed(time); };

  useEffect(() => { if (sessionStorage.getItem('midnight-relay-booted')) setBoot(false); const timer = setTimeout(() => { setBoot(false); sessionStorage.setItem('midnight-relay-booted', 'yes'); }, 2500); return () => clearTimeout(timer); }, []);
  useEffect(() => { const script = document.createElement('script'); script.src = 'https://www.youtube.com/iframe_api'; document.body.appendChild(script); window.onYouTubeIframeAPIReady = () => { player.current = new window.YT.Player(playerMount.current!, { width: '100%', height: '100%', videoId: tracks[0].videoId, playerVars: { playsinline: 1, rel: 0, modestbranding: 1 }, events: { onReady: (e: any) => e.target.setVolume(volume), onStateChange: (e: any) => { if (e.data === window.YT.PlayerState.ENDED) load(activeRef.current + 1); setPlaying(e.data === window.YT.PlayerState.PLAYING); }, onError: () => load(activeRef.current + 1) } }); }; return () => script.remove(); }, [load]);
  useEffect(() => { const id = setInterval(() => { setClock(stamp()); if (player.current?.getCurrentTime) { setElapsed(player.current.getCurrentTime() || 0); setDuration(player.current.getDuration() || 0); } }, 500); return () => clearInterval(id); }, []);
  useEffect(() => { const id = sessionStorage.getItem('relay-id') || crypto.randomUUID(); sessionStorage.setItem('relay-id', id); const ping = () => fetch('/api/presence', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) }).then(r => r.json()).then(d => setListeners(d.count)).catch(() => {}); ping(); const timer = setInterval(ping, 20_000); return () => clearInterval(timer); }, []);
  useEffect(() => { const fallback = () => fetch('https://api.open-meteo.com/v1/forecast?latitude=12.97&longitude=77.59&current=temperature_2m,weather_code').then(r => r.json()).then(d => setWeather(`${Math.round(d.current.temperature_2m)}° ${d.current.weather_code < 3 ? 'Clear' : 'Cloudy'}`)).catch(() => {}); navigator.geolocation?.getCurrentPosition(p => fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.coords.latitude}&longitude=${p.coords.longitude}&current=temperature_2m,weather_code`).then(r => r.json()).then(d => setWeather(`${Math.round(d.current.temperature_2m)}° Local`)).catch(fallback), fallback, { timeout: 4000 }); }, []);
  useEffect(() => { const wake = () => { lastInput.current = Date.now(); if (saver) setSaver(false); }; ['pointerdown', 'pointermove', 'keydown', 'touchstart'].forEach(e => window.addEventListener(e, wake)); const t = setInterval(() => setSaver(Date.now() - lastInput.current > 90_000), 1000); return () => { clearInterval(t); ['pointerdown', 'pointermove', 'keydown', 'touchstart'].forEach(e => window.removeEventListener(e, wake)); }; }, [saver]);
  const cycleSpeed = () => { const next = speeds[(speeds.indexOf(speed) + 1) % speeds.length]; setSpeed(next); player.current?.setPlaybackRate(next); };
  const refresh = () => { setShimmer(true); setContext(null); setTimeout(() => setShimmer(false), 900); };

  return <main className="stage" onContextMenu={e => { e.preventDefault(); setContext({ x: e.clientX, y: e.clientY }); }} onPointerDown={() => context && setContext(null)}>
    <div className={`scene ${shimmer ? 'shimmer' : ''}`}>
      <div className="scanlines" /><div className="masthead"><h1>MIDNIGHT RELAY</h1><p>the radio is low, the city is finally quiet</p></div>
      <div className="online"><span />{listeners} night owls online</div>
      <aside className="desktop-icons"><button onClick={() => setPlaylist(true)}><Glyph type="tower" /><span>Radio Tower</span></button><button><Glyph type="bin" /><span>Paper Basket</span></button><button onClick={() => setPlaylist(true)}><Glyph type="tape" /><span>Late Night Mixes</span></button><button><Glyph type="folder" /><span>Letters (7)</span></button><button><Glyph type="folder peach" /><span>पोस्टकार्ड</span></button><button className="secret"><Glyph type="note" /><span>for the train home.txt</span></button></aside>
      {playlist && <WindowBox title="MIDNIGHT PLAYLIST" className="playlist" onClose={() => setPlaylist(false)}><div className="playlist-head">queued for the small hours <span>▾</span></div><div className="tracks">{tracks.map((song, i) => <button key={song.title} className={i === active ? 'selected' : ''} onClick={() => load(i)}><em>{String(i + 1).padStart(2, '0')}</em><span><b>{song.title}</b><small>{song.artist} · {song.year}</small></span><time>{i === active && duration ? niceTime(duration) : ['3:42', '4:06', '3:29', '4:12'][i]}</time></button>)}</div></WindowBox>}
      <div className="now-window" style={nowPos ? { left: nowPos.x, top: nowPos.y, right: 'auto' } : undefined}><div className="now-title" onPointerDown={(e) => { const x = e.clientX - (e.currentTarget.parentElement?.getBoundingClientRect().left || 0), y = e.clientY - (e.currentTarget.parentElement?.getBoundingClientRect().top || 0); const move = (event: PointerEvent) => setNowPos({ x: Math.max(0, Math.min(window.innerWidth - 230, event.clientX - x)), y: Math.max(0, Math.min(window.innerHeight - 180, event.clientY - y)) }); const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); }}> <span className={playing ? 'red-light on' : 'red-light'} /> NOW PLAYING <small>official video · drag me</small></div><div className="video-wrap" ref={playerMount} /><div className="now-caption"><span>{track.title}</span><small>{track.artist} · {track.year}</small></div></div>
      <div className="player-deck"><div className="led">{niceTime(elapsed)}</div><div className="song-scroll"><span>{track.title} — {track.artist} · {track.year} · {track.title} — {track.artist}</span></div><div className="transport"><button onClick={() => load(active - 1)}>◀◀</button><button onClick={() => seek(Math.max(0, elapsed - 10))}>↶10</button><button className="play" onClick={toggle}>{playing ? 'Ⅱ' : '▶'}</button><button onClick={() => seek(Math.min(duration, elapsed + 10))}>10↷</button><button onClick={() => load(active + 1)}>▶▶</button></div><button className="speed" onClick={cycleSpeed}>{speed}×</button><input aria-label="Seek song" className="seek" type="range" min="0" max={duration || 100} value={elapsed} onPointerDown={() => dragged.current = true} onPointerUp={() => dragged.current = false} onChange={e => { const val = Number(e.target.value); setElapsed(val); if (dragged.current) seek(val); }} /><div className={`equalizer ${playing ? 'dancing' : ''}`}>{Array.from({ length: 12 }).map((_, i) => <i key={i} style={{ animationDelay: `${i * -.13}s` }} />)}</div><label className="volume">VOL<input aria-label="Volume" type="range" value={volume} onChange={e => { const v = Number(e.target.value); setVolume(v); player.current?.setVolume(v); }} /></label></div>
      <footer className="taskbar"><button className="start" onClick={() => setMenu(!menu)}><Glyph type="spark" />start</button><button className="task" onClick={() => setPlaylist(true)}><i className="mini-disc" />{track.title}</button><div className="tray"><span>☾ {weather}</span><span>◉ {listeners}</span><time>{clock}</time></div></footer>
      {menu && <div className="start-menu"><div className="menu-brand">MIDNIGHT<br />RELAY</div><div className="menu-body"><div className="menu-now"><small>NOW PLAYING</small><b>{track.title}</b><span>UP NEXT: {tracks[(active + 1) % tracks.length].title}</span></div><p>{dayStamp()}<br /><b>{clock} IST</b></p><p className="weather-menu">☾ {weather} <small>via Open-Meteo</small></p><button>ⓘ About <span>made by Ratna after midnight</span></button><button className="shutdown" onClick={() => setOff(true)}>⏻ Shut Down</button></div></div>}
      {context && <div className="context" style={{ left: context.x, top: context.y }}><button onClick={refresh}>↻ Refresh wallpaper</button><button onClick={() => setPlaylist(true)}>Open playlist</button></div>}
      {off && <div className="shutdown-screen" onClick={() => setOff(false)}><div><span>◆</span><p>It is safe to dream in another tab.</p><small>click anywhere to return</small></div></div>}
      {saver && <div className="saver"><div>MIDNIGHT<br />RELAY</div><small>move to return</small></div>}
    </div>
    {boot && <div className="boot" onClick={() => { setBoot(false); sessionStorage.setItem('midnight-relay-booted', 'yes'); }}><div><h2>MIDNIGHT RELAY</h2><p>tuning the frequency...</p><div className="boot-bar"><i /></div><small>click to skip</small></div></div>}
  </main>;
}
